services:
  db:
    image: postgres:15
    container_name: projects-db-1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tango
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  redis:
    image: redis:7
    ports: ["6379:6379"]
    command: ["redis-server","--appendonly","yes"]
  
  server:
    build:
      context: ./apps/server
      dockerfile: Dockerfile
    env_file:
      - ./apps/server/.env
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/tango
      - REDIS_URL=redis://redis:6379
      - PHONE_ENC_KEY=${PHONE_ENC_KEY:-dev-32-bytes-minimum-secret-key}
      - NODE_ENV=development
      - KYC_MIN_AGE=50
      - OTP_RATE_PER_PHONE=5
      - OTP_RATE_PHONE_WINDOW=3600
      - OTP_RATE_PER_IP=10
      - OTP_RATE_IP_WINDOW=3600
      - OTP_RESEND_COOLDOWN_SEC=60
    depends_on: [db, redis]
    ports: ["4100:4100"]
    volumes:
      - ./apps/server:/app
      - /app/node_modules
    command: ["npm", "run", "dev"]

volumes:
  pgdata:
