services:
  db:
    image: postgres:15
    container_name: projects-db-1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tango
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  redis:
    image: redis:7
    ports: ["6379:6379"]
    command: ["redis-server","--appendonly","yes"]
  
  server:
    build:
      context: ./apps/server
      dockerfile: Dockerfile
    env_file:
      - ./apps/server/.env
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/tango
      - REDIS_URL=redis://redis:6379
      - PHONE_ENC_KEY=${PHONE_ENC_KEY}
    depends_on: [db, redis]
    ports: ["4100:4100"]
    command: ["node","dist/index.js"]

volumes:
  pgdata:
