version: '3.8'

services:
  server:
    environment:
      - NODE_ENV=production
      - PORT=4100
      - TRUST_PROXY=1
    secrets:
      - database_url
      - phone_enc_key
      - redis_url
    deploy:
      resources:
        limits: { cpus: "1.0", memory: "1g" }

secrets:
  database_url:
    file: ./secrets/database_url.txt
  phone_enc_key:
    file: ./secrets/phone_enc_key.txt
  redis_url:
    file: ./secrets/redis_url.txt
