server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # ===== 애플리케이션 로그 수집 =====
  - job_name: tango-server
    static_configs:
      - targets:
          - localhost
        labels:
          service: tango-server
          env: development
          __path__: /var/log/apps/*.log
    
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            type: type
            status: status
            code: code
            requestId: requestId
            phone: phone
            ip: ip
            latencyMs: latencyMs
            error: error
      
      - labels:
          level:
          type:
          status:
          code:
      
      - timestamp:
          source: timestamp
          format: RFC3339Nano
      
      - output:
          source: message

  # ===== 시스템 로그 수집 =====
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          service: system
          __path__: /var/log/syslog
