-- V001__users.sql
-- MySQL 8.0 / InnoDB / utf8mb4
DROP TABLE IF EXISTS users;
CREATE TABLE users (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  phone_e164_norm VARCHAR(20) NOT NULL UNIQUE,
  phone_enc VARBINARY(256) NULL,
  name VARCHAR(100) NULL,
  birth CHAR(8) NULL, -- YYYYMMDD
  is_kyc_verified TINYINT(1) NOT NULL DEFAULT 0,
  kyc_verified_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_users_phone (phone_e164_norm)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
