
ALTER TABLE users
    ADD COLUMN IF NOT EXISTS region_code VARCHAR(20),
    ADD COLUMN IF NOT EXISTS region_label TEXT,
    ADD COLUMN IF NOT EXISTS region_lat DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS region_lng DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS region_source TEXT;
