name: PR CI

on:
  pull_request:
    branches: [ main, develop ]
  workflow_call:
    inputs:
      node-version:
        description: 'Node.js version to use'
        required: false
        default: '18'
        type: string

jobs:
  ci:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18, 20]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Type check
      run: npm run ci:typecheck
      
    - name: Lint
      run: npm run ci:lint
      
    - name: Test
      run: npm run ci:test
      
    - name: Build
      run: npm run ci:build
      
    - name: Format check
      run: npm run ci:format:check
